base: &base
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: locatorboard
  password:

development:
  <<: *base
  database: locatorboard_dev

test:
  <<: *base
  database: locatorboard_test

production:
  <<: *base
  database: locatorboard_prod
